### ISSUE TITLE
Non-destructor variant

### ISSUE THREAD

**Issue by milsorm** [JanGalek/CombineFiles#1]
I've changed in my code usage of __destruct to __toString() for better use-case in @layout:

```
/** @var string */
private $compiled;

public function __toString()
{
    if ( !isset( $this->compiled ) )
        $this->compiled = $this->compiler->compile($this->getFiles(), $this->root, $this->path, $this->name, $this->type);
     return $this->compiled;
}
```

Because when used as service in DI it survives for the whole time (not only in one function scope). Also printing anything in destructor is ... ehm ... unexpected and ugly.

As service in DI I prepared this extension (I didn't recognize your ones):

```
use Nette;

class Combinator extends Nette\DI\CompilerExtension
{
    private $defaults
        = [
            'root_path'  => '%wwwDir%',
            'local_path' => 'css',
            'files'      => [],
        ];

    public function loadConfiguration () {
        $config = $this->_getConfig();

        $builder = $this->getContainerBuilder();

        $combinatorDef = $builder->addDefinition( $this->prefix( 'combine' ) )
                                 ->setClass( 'Galek\Utils\CombineFiles' )
                                 ->setArguments( [
                                     $config[ 'root_path' ],
                                     $config[ 'local_path' ],
                                 ] );

        if ( is_array( $config[ 'files' ] ) )
            $combinatorDef->addSetup( 'addFiles', [ $config[ 'files' ] ] );
    }

    private function _getConfig () {
        $config = $this->validateConfig( $this->defaults, $this->config );

        $config[ 'root_path' ] = Nette\DI\Helpers::expand( $config[ 'root_path' ], $this->getContainerBuilder()->parameters );

        return $config;
    }

}
```

so use in config.neon is pretty simple:

```
extensions:
    cssCombinator: App\Handlers\Combinator
    jsCombinator: App\Handlers\Combinator

cssCombinator:
    root_path: %wwwDir%
    local_path: css
    files:
        - main.css
        - top.css

jsCombinator:
    root_path: %wwwDir%
    local_path: js
    files:
        - main.js
```

In BasePresenter I only retrieve service from context (two services with same type = cannot use DI directly).

But - one thing is pitty - it is loading only file under 8192 B or first part of CSS until this border. And that is really bad so I cannot use it (after more than hour of preparation).

So questions:
- can you change __destruct behaviour to something more non-ugly?
- add doc to your extension use in DI or use above
- what with 8192 B? something what I miss?
